package com.plc.gjw.domain;

import java.util.Date;

public class BackStock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_back_stock.id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_back_stock.stock_code
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String stockCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_back_stock.merchant_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Long merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_back_stock.product_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_back_stock.bar_code
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String barCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_back_stock.erp_code
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String erpCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_back_stock.product_name
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_back_stock.stock_count
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Integer stockCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_back_stock.lock_count
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Integer lockCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_back_stock.operator
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_back_stock.operator_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Long operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_back_stock.created_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_back_stock.modified_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Date modifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_back_stock.id
     *
     * @return the value of innovation_back_stock.id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_back_stock.id
     *
     * @param id the value for innovation_back_stock.id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_back_stock.stock_code
     *
     * @return the value of innovation_back_stock.stock_code
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getStockCode() {
        return stockCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_back_stock.stock_code
     *
     * @param stockCode the value for innovation_back_stock.stock_code
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setStockCode(String stockCode) {
        this.stockCode = stockCode == null ? null : stockCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_back_stock.merchant_id
     *
     * @return the value of innovation_back_stock.merchant_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_back_stock.merchant_id
     *
     * @param merchantId the value for innovation_back_stock.merchant_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_back_stock.product_id
     *
     * @return the value of innovation_back_stock.product_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_back_stock.product_id
     *
     * @param productId the value for innovation_back_stock.product_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_back_stock.bar_code
     *
     * @return the value of innovation_back_stock.bar_code
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_back_stock.bar_code
     *
     * @param barCode the value for innovation_back_stock.bar_code
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_back_stock.erp_code
     *
     * @return the value of innovation_back_stock.erp_code
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getErpCode() {
        return erpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_back_stock.erp_code
     *
     * @param erpCode the value for innovation_back_stock.erp_code
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setErpCode(String erpCode) {
        this.erpCode = erpCode == null ? null : erpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_back_stock.product_name
     *
     * @return the value of innovation_back_stock.product_name
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_back_stock.product_name
     *
     * @param productName the value for innovation_back_stock.product_name
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_back_stock.stock_count
     *
     * @return the value of innovation_back_stock.stock_count
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Integer getStockCount() {
        return stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_back_stock.stock_count
     *
     * @param stockCount the value for innovation_back_stock.stock_count
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setStockCount(Integer stockCount) {
        this.stockCount = stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_back_stock.lock_count
     *
     * @return the value of innovation_back_stock.lock_count
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Integer getLockCount() {
        return lockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_back_stock.lock_count
     *
     * @param lockCount the value for innovation_back_stock.lock_count
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setLockCount(Integer lockCount) {
        this.lockCount = lockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_back_stock.operator
     *
     * @return the value of innovation_back_stock.operator
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_back_stock.operator
     *
     * @param operator the value for innovation_back_stock.operator
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_back_stock.operator_id
     *
     * @return the value of innovation_back_stock.operator_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_back_stock.operator_id
     *
     * @param operatorId the value for innovation_back_stock.operator_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_back_stock.created_date
     *
     * @return the value of innovation_back_stock.created_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_back_stock.created_date
     *
     * @param createdDate the value for innovation_back_stock.created_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_back_stock.modified_date
     *
     * @return the value of innovation_back_stock.modified_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_back_stock.modified_date
     *
     * @param modifiedDate the value for innovation_back_stock.modified_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
}