package com.plc.gjw.domain;

import java.math.BigDecimal;
import java.util.Date;

public class EplMerchant {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.merchant_name
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String merchantName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.merchant_identify
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String merchantIdentify;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.phone
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.address
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.channel_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private Long channelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.type_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private Long typeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.created_date
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.modified_date
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private Date modifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.merchant_logo
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String merchantLogo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.merchant_banner
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String merchantBanner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.merchant_long
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private BigDecimal merchantLong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.merchant_latitude
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private BigDecimal merchantLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.merchant_secretkey
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String merchantSecretkey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.if_open_erp
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String ifOpenErp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.if_open_qrcode
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String ifOpenQrcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.qrcode_type
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String qrcodeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.qrcode_url
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String qrcodeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.merchant_shorthand
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String merchantShorthand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.merchant_logo_key
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String merchantLogoKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.operator
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.operator_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private Long operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.province_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private Integer provinceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.province_name
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String provinceName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.city_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private Integer cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.city_name
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.county_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private Integer countyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.county_name
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String countyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.town_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private Integer townId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column epl_merchant.town_name
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    private String townName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.id
     *
     * @return the value of epl_merchant.id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.id
     *
     * @param id the value for epl_merchant.id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.merchant_name
     *
     * @return the value of epl_merchant.merchant_name
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getMerchantName() {
        return merchantName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.merchant_name
     *
     * @param merchantName the value for epl_merchant.merchant_name
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setMerchantName(String merchantName) {
        this.merchantName = merchantName == null ? null : merchantName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.merchant_identify
     *
     * @return the value of epl_merchant.merchant_identify
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getMerchantIdentify() {
        return merchantIdentify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.merchant_identify
     *
     * @param merchantIdentify the value for epl_merchant.merchant_identify
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setMerchantIdentify(String merchantIdentify) {
        this.merchantIdentify = merchantIdentify == null ? null : merchantIdentify.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.phone
     *
     * @return the value of epl_merchant.phone
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.phone
     *
     * @param phone the value for epl_merchant.phone
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.address
     *
     * @return the value of epl_merchant.address
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.address
     *
     * @param address the value for epl_merchant.address
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.channel_id
     *
     * @return the value of epl_merchant.channel_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public Long getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.channel_id
     *
     * @param channelId the value for epl_merchant.channel_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setChannelId(Long channelId) {
        this.channelId = channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.type_id
     *
     * @return the value of epl_merchant.type_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.type_id
     *
     * @param typeId the value for epl_merchant.type_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.created_date
     *
     * @return the value of epl_merchant.created_date
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.created_date
     *
     * @param createdDate the value for epl_merchant.created_date
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.modified_date
     *
     * @return the value of epl_merchant.modified_date
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.modified_date
     *
     * @param modifiedDate the value for epl_merchant.modified_date
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.merchant_logo
     *
     * @return the value of epl_merchant.merchant_logo
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getMerchantLogo() {
        return merchantLogo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.merchant_logo
     *
     * @param merchantLogo the value for epl_merchant.merchant_logo
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setMerchantLogo(String merchantLogo) {
        this.merchantLogo = merchantLogo == null ? null : merchantLogo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.merchant_banner
     *
     * @return the value of epl_merchant.merchant_banner
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getMerchantBanner() {
        return merchantBanner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.merchant_banner
     *
     * @param merchantBanner the value for epl_merchant.merchant_banner
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setMerchantBanner(String merchantBanner) {
        this.merchantBanner = merchantBanner == null ? null : merchantBanner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.merchant_long
     *
     * @return the value of epl_merchant.merchant_long
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public BigDecimal getMerchantLong() {
        return merchantLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.merchant_long
     *
     * @param merchantLong the value for epl_merchant.merchant_long
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setMerchantLong(BigDecimal merchantLong) {
        this.merchantLong = merchantLong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.merchant_latitude
     *
     * @return the value of epl_merchant.merchant_latitude
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public BigDecimal getMerchantLatitude() {
        return merchantLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.merchant_latitude
     *
     * @param merchantLatitude the value for epl_merchant.merchant_latitude
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setMerchantLatitude(BigDecimal merchantLatitude) {
        this.merchantLatitude = merchantLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.merchant_secretkey
     *
     * @return the value of epl_merchant.merchant_secretkey
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getMerchantSecretkey() {
        return merchantSecretkey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.merchant_secretkey
     *
     * @param merchantSecretkey the value for epl_merchant.merchant_secretkey
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setMerchantSecretkey(String merchantSecretkey) {
        this.merchantSecretkey = merchantSecretkey == null ? null : merchantSecretkey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.if_open_erp
     *
     * @return the value of epl_merchant.if_open_erp
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getIfOpenErp() {
        return ifOpenErp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.if_open_erp
     *
     * @param ifOpenErp the value for epl_merchant.if_open_erp
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setIfOpenErp(String ifOpenErp) {
        this.ifOpenErp = ifOpenErp == null ? null : ifOpenErp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.if_open_qrcode
     *
     * @return the value of epl_merchant.if_open_qrcode
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getIfOpenQrcode() {
        return ifOpenQrcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.if_open_qrcode
     *
     * @param ifOpenQrcode the value for epl_merchant.if_open_qrcode
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setIfOpenQrcode(String ifOpenQrcode) {
        this.ifOpenQrcode = ifOpenQrcode == null ? null : ifOpenQrcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.qrcode_type
     *
     * @return the value of epl_merchant.qrcode_type
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getQrcodeType() {
        return qrcodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.qrcode_type
     *
     * @param qrcodeType the value for epl_merchant.qrcode_type
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setQrcodeType(String qrcodeType) {
        this.qrcodeType = qrcodeType == null ? null : qrcodeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.qrcode_url
     *
     * @return the value of epl_merchant.qrcode_url
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getQrcodeUrl() {
        return qrcodeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.qrcode_url
     *
     * @param qrcodeUrl the value for epl_merchant.qrcode_url
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setQrcodeUrl(String qrcodeUrl) {
        this.qrcodeUrl = qrcodeUrl == null ? null : qrcodeUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.merchant_shorthand
     *
     * @return the value of epl_merchant.merchant_shorthand
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getMerchantShorthand() {
        return merchantShorthand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.merchant_shorthand
     *
     * @param merchantShorthand the value for epl_merchant.merchant_shorthand
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setMerchantShorthand(String merchantShorthand) {
        this.merchantShorthand = merchantShorthand == null ? null : merchantShorthand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.merchant_logo_key
     *
     * @return the value of epl_merchant.merchant_logo_key
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getMerchantLogoKey() {
        return merchantLogoKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.merchant_logo_key
     *
     * @param merchantLogoKey the value for epl_merchant.merchant_logo_key
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setMerchantLogoKey(String merchantLogoKey) {
        this.merchantLogoKey = merchantLogoKey == null ? null : merchantLogoKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.operator
     *
     * @return the value of epl_merchant.operator
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.operator
     *
     * @param operator the value for epl_merchant.operator
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.operator_id
     *
     * @return the value of epl_merchant.operator_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.operator_id
     *
     * @param operatorId the value for epl_merchant.operator_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.province_id
     *
     * @return the value of epl_merchant.province_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public Integer getProvinceId() {
        return provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.province_id
     *
     * @param provinceId the value for epl_merchant.province_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.province_name
     *
     * @return the value of epl_merchant.province_name
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getProvinceName() {
        return provinceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.province_name
     *
     * @param provinceName the value for epl_merchant.province_name
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName == null ? null : provinceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.city_id
     *
     * @return the value of epl_merchant.city_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.city_id
     *
     * @param cityId the value for epl_merchant.city_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.city_name
     *
     * @return the value of epl_merchant.city_name
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.city_name
     *
     * @param cityName the value for epl_merchant.city_name
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.county_id
     *
     * @return the value of epl_merchant.county_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public Integer getCountyId() {
        return countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.county_id
     *
     * @param countyId the value for epl_merchant.county_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setCountyId(Integer countyId) {
        this.countyId = countyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.county_name
     *
     * @return the value of epl_merchant.county_name
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getCountyName() {
        return countyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.county_name
     *
     * @param countyName the value for epl_merchant.county_name
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setCountyName(String countyName) {
        this.countyName = countyName == null ? null : countyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.town_id
     *
     * @return the value of epl_merchant.town_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public Integer getTownId() {
        return townId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.town_id
     *
     * @param townId the value for epl_merchant.town_id
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setTownId(Integer townId) {
        this.townId = townId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column epl_merchant.town_name
     *
     * @return the value of epl_merchant.town_name
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getTownName() {
        return townName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column epl_merchant.town_name
     *
     * @param townName the value for epl_merchant.town_name
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setTownName(String townName) {
        this.townName = townName == null ? null : townName.trim();
    }
}