package com.plc.gjw.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EplMerchantExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public EplMerchantExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMerchantNameIsNull() {
            addCriterion("merchant_name is null");
            return (Criteria) this;
        }

        public Criteria andMerchantNameIsNotNull() {
            addCriterion("merchant_name is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantNameEqualTo(String value) {
            addCriterion("merchant_name =", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotEqualTo(String value) {
            addCriterion("merchant_name <>", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameGreaterThan(String value) {
            addCriterion("merchant_name >", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameGreaterThanOrEqualTo(String value) {
            addCriterion("merchant_name >=", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameLessThan(String value) {
            addCriterion("merchant_name <", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameLessThanOrEqualTo(String value) {
            addCriterion("merchant_name <=", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameLike(String value) {
            addCriterion("merchant_name like", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotLike(String value) {
            addCriterion("merchant_name not like", value, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameIn(List<String> values) {
            addCriterion("merchant_name in", values, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotIn(List<String> values) {
            addCriterion("merchant_name not in", values, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameBetween(String value1, String value2) {
            addCriterion("merchant_name between", value1, value2, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantNameNotBetween(String value1, String value2) {
            addCriterion("merchant_name not between", value1, value2, "merchantName");
            return (Criteria) this;
        }

        public Criteria andMerchantIdentifyIsNull() {
            addCriterion("merchant_identify is null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdentifyIsNotNull() {
            addCriterion("merchant_identify is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdentifyEqualTo(String value) {
            addCriterion("merchant_identify =", value, "merchantIdentify");
            return (Criteria) this;
        }

        public Criteria andMerchantIdentifyNotEqualTo(String value) {
            addCriterion("merchant_identify <>", value, "merchantIdentify");
            return (Criteria) this;
        }

        public Criteria andMerchantIdentifyGreaterThan(String value) {
            addCriterion("merchant_identify >", value, "merchantIdentify");
            return (Criteria) this;
        }

        public Criteria andMerchantIdentifyGreaterThanOrEqualTo(String value) {
            addCriterion("merchant_identify >=", value, "merchantIdentify");
            return (Criteria) this;
        }

        public Criteria andMerchantIdentifyLessThan(String value) {
            addCriterion("merchant_identify <", value, "merchantIdentify");
            return (Criteria) this;
        }

        public Criteria andMerchantIdentifyLessThanOrEqualTo(String value) {
            addCriterion("merchant_identify <=", value, "merchantIdentify");
            return (Criteria) this;
        }

        public Criteria andMerchantIdentifyLike(String value) {
            addCriterion("merchant_identify like", value, "merchantIdentify");
            return (Criteria) this;
        }

        public Criteria andMerchantIdentifyNotLike(String value) {
            addCriterion("merchant_identify not like", value, "merchantIdentify");
            return (Criteria) this;
        }

        public Criteria andMerchantIdentifyIn(List<String> values) {
            addCriterion("merchant_identify in", values, "merchantIdentify");
            return (Criteria) this;
        }

        public Criteria andMerchantIdentifyNotIn(List<String> values) {
            addCriterion("merchant_identify not in", values, "merchantIdentify");
            return (Criteria) this;
        }

        public Criteria andMerchantIdentifyBetween(String value1, String value2) {
            addCriterion("merchant_identify between", value1, value2, "merchantIdentify");
            return (Criteria) this;
        }

        public Criteria andMerchantIdentifyNotBetween(String value1, String value2) {
            addCriterion("merchant_identify not between", value1, value2, "merchantIdentify");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNull() {
            addCriterion("channel_id is null");
            return (Criteria) this;
        }

        public Criteria andChannelIdIsNotNull() {
            addCriterion("channel_id is not null");
            return (Criteria) this;
        }

        public Criteria andChannelIdEqualTo(Long value) {
            addCriterion("channel_id =", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotEqualTo(Long value) {
            addCriterion("channel_id <>", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThan(Long value) {
            addCriterion("channel_id >", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdGreaterThanOrEqualTo(Long value) {
            addCriterion("channel_id >=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThan(Long value) {
            addCriterion("channel_id <", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdLessThanOrEqualTo(Long value) {
            addCriterion("channel_id <=", value, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdIn(List<Long> values) {
            addCriterion("channel_id in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotIn(List<Long> values) {
            addCriterion("channel_id not in", values, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdBetween(Long value1, Long value2) {
            addCriterion("channel_id between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andChannelIdNotBetween(Long value1, Long value2) {
            addCriterion("channel_id not between", value1, value2, "channelId");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNull() {
            addCriterion("type_id is null");
            return (Criteria) this;
        }

        public Criteria andTypeIdIsNotNull() {
            addCriterion("type_id is not null");
            return (Criteria) this;
        }

        public Criteria andTypeIdEqualTo(Long value) {
            addCriterion("type_id =", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotEqualTo(Long value) {
            addCriterion("type_id <>", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThan(Long value) {
            addCriterion("type_id >", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("type_id >=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThan(Long value) {
            addCriterion("type_id <", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdLessThanOrEqualTo(Long value) {
            addCriterion("type_id <=", value, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdIn(List<Long> values) {
            addCriterion("type_id in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotIn(List<Long> values) {
            addCriterion("type_id not in", values, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdBetween(Long value1, Long value2) {
            addCriterion("type_id between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andTypeIdNotBetween(Long value1, Long value2) {
            addCriterion("type_id not between", value1, value2, "typeId");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("created_date is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("created_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("created_date =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("created_date <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("created_date >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("created_date >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("created_date <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("created_date <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("created_date in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("created_date not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("created_date between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("created_date not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNull() {
            addCriterion("modified_date is null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNotNull() {
            addCriterion("modified_date is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateEqualTo(Date value) {
            addCriterion("modified_date =", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotEqualTo(Date value) {
            addCriterion("modified_date <>", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThan(Date value) {
            addCriterion("modified_date >", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_date >=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThan(Date value) {
            addCriterion("modified_date <", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("modified_date <=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIn(List<Date> values) {
            addCriterion("modified_date in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotIn(List<Date> values) {
            addCriterion("modified_date not in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateBetween(Date value1, Date value2) {
            addCriterion("modified_date between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("modified_date not between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoIsNull() {
            addCriterion("merchant_logo is null");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoIsNotNull() {
            addCriterion("merchant_logo is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoEqualTo(String value) {
            addCriterion("merchant_logo =", value, "merchantLogo");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoNotEqualTo(String value) {
            addCriterion("merchant_logo <>", value, "merchantLogo");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoGreaterThan(String value) {
            addCriterion("merchant_logo >", value, "merchantLogo");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoGreaterThanOrEqualTo(String value) {
            addCriterion("merchant_logo >=", value, "merchantLogo");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoLessThan(String value) {
            addCriterion("merchant_logo <", value, "merchantLogo");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoLessThanOrEqualTo(String value) {
            addCriterion("merchant_logo <=", value, "merchantLogo");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoLike(String value) {
            addCriterion("merchant_logo like", value, "merchantLogo");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoNotLike(String value) {
            addCriterion("merchant_logo not like", value, "merchantLogo");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoIn(List<String> values) {
            addCriterion("merchant_logo in", values, "merchantLogo");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoNotIn(List<String> values) {
            addCriterion("merchant_logo not in", values, "merchantLogo");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoBetween(String value1, String value2) {
            addCriterion("merchant_logo between", value1, value2, "merchantLogo");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoNotBetween(String value1, String value2) {
            addCriterion("merchant_logo not between", value1, value2, "merchantLogo");
            return (Criteria) this;
        }

        public Criteria andMerchantBannerIsNull() {
            addCriterion("merchant_banner is null");
            return (Criteria) this;
        }

        public Criteria andMerchantBannerIsNotNull() {
            addCriterion("merchant_banner is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantBannerEqualTo(String value) {
            addCriterion("merchant_banner =", value, "merchantBanner");
            return (Criteria) this;
        }

        public Criteria andMerchantBannerNotEqualTo(String value) {
            addCriterion("merchant_banner <>", value, "merchantBanner");
            return (Criteria) this;
        }

        public Criteria andMerchantBannerGreaterThan(String value) {
            addCriterion("merchant_banner >", value, "merchantBanner");
            return (Criteria) this;
        }

        public Criteria andMerchantBannerGreaterThanOrEqualTo(String value) {
            addCriterion("merchant_banner >=", value, "merchantBanner");
            return (Criteria) this;
        }

        public Criteria andMerchantBannerLessThan(String value) {
            addCriterion("merchant_banner <", value, "merchantBanner");
            return (Criteria) this;
        }

        public Criteria andMerchantBannerLessThanOrEqualTo(String value) {
            addCriterion("merchant_banner <=", value, "merchantBanner");
            return (Criteria) this;
        }

        public Criteria andMerchantBannerLike(String value) {
            addCriterion("merchant_banner like", value, "merchantBanner");
            return (Criteria) this;
        }

        public Criteria andMerchantBannerNotLike(String value) {
            addCriterion("merchant_banner not like", value, "merchantBanner");
            return (Criteria) this;
        }

        public Criteria andMerchantBannerIn(List<String> values) {
            addCriterion("merchant_banner in", values, "merchantBanner");
            return (Criteria) this;
        }

        public Criteria andMerchantBannerNotIn(List<String> values) {
            addCriterion("merchant_banner not in", values, "merchantBanner");
            return (Criteria) this;
        }

        public Criteria andMerchantBannerBetween(String value1, String value2) {
            addCriterion("merchant_banner between", value1, value2, "merchantBanner");
            return (Criteria) this;
        }

        public Criteria andMerchantBannerNotBetween(String value1, String value2) {
            addCriterion("merchant_banner not between", value1, value2, "merchantBanner");
            return (Criteria) this;
        }

        public Criteria andMerchantLongIsNull() {
            addCriterion("merchant_long is null");
            return (Criteria) this;
        }

        public Criteria andMerchantLongIsNotNull() {
            addCriterion("merchant_long is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantLongEqualTo(BigDecimal value) {
            addCriterion("merchant_long =", value, "merchantLong");
            return (Criteria) this;
        }

        public Criteria andMerchantLongNotEqualTo(BigDecimal value) {
            addCriterion("merchant_long <>", value, "merchantLong");
            return (Criteria) this;
        }

        public Criteria andMerchantLongGreaterThan(BigDecimal value) {
            addCriterion("merchant_long >", value, "merchantLong");
            return (Criteria) this;
        }

        public Criteria andMerchantLongGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("merchant_long >=", value, "merchantLong");
            return (Criteria) this;
        }

        public Criteria andMerchantLongLessThan(BigDecimal value) {
            addCriterion("merchant_long <", value, "merchantLong");
            return (Criteria) this;
        }

        public Criteria andMerchantLongLessThanOrEqualTo(BigDecimal value) {
            addCriterion("merchant_long <=", value, "merchantLong");
            return (Criteria) this;
        }

        public Criteria andMerchantLongIn(List<BigDecimal> values) {
            addCriterion("merchant_long in", values, "merchantLong");
            return (Criteria) this;
        }

        public Criteria andMerchantLongNotIn(List<BigDecimal> values) {
            addCriterion("merchant_long not in", values, "merchantLong");
            return (Criteria) this;
        }

        public Criteria andMerchantLongBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("merchant_long between", value1, value2, "merchantLong");
            return (Criteria) this;
        }

        public Criteria andMerchantLongNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("merchant_long not between", value1, value2, "merchantLong");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeIsNull() {
            addCriterion("merchant_latitude is null");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeIsNotNull() {
            addCriterion("merchant_latitude is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeEqualTo(BigDecimal value) {
            addCriterion("merchant_latitude =", value, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeNotEqualTo(BigDecimal value) {
            addCriterion("merchant_latitude <>", value, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeGreaterThan(BigDecimal value) {
            addCriterion("merchant_latitude >", value, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("merchant_latitude >=", value, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeLessThan(BigDecimal value) {
            addCriterion("merchant_latitude <", value, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("merchant_latitude <=", value, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeIn(List<BigDecimal> values) {
            addCriterion("merchant_latitude in", values, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeNotIn(List<BigDecimal> values) {
            addCriterion("merchant_latitude not in", values, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("merchant_latitude between", value1, value2, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantLatitudeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("merchant_latitude not between", value1, value2, "merchantLatitude");
            return (Criteria) this;
        }

        public Criteria andMerchantSecretkeyIsNull() {
            addCriterion("merchant_secretkey is null");
            return (Criteria) this;
        }

        public Criteria andMerchantSecretkeyIsNotNull() {
            addCriterion("merchant_secretkey is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantSecretkeyEqualTo(String value) {
            addCriterion("merchant_secretkey =", value, "merchantSecretkey");
            return (Criteria) this;
        }

        public Criteria andMerchantSecretkeyNotEqualTo(String value) {
            addCriterion("merchant_secretkey <>", value, "merchantSecretkey");
            return (Criteria) this;
        }

        public Criteria andMerchantSecretkeyGreaterThan(String value) {
            addCriterion("merchant_secretkey >", value, "merchantSecretkey");
            return (Criteria) this;
        }

        public Criteria andMerchantSecretkeyGreaterThanOrEqualTo(String value) {
            addCriterion("merchant_secretkey >=", value, "merchantSecretkey");
            return (Criteria) this;
        }

        public Criteria andMerchantSecretkeyLessThan(String value) {
            addCriterion("merchant_secretkey <", value, "merchantSecretkey");
            return (Criteria) this;
        }

        public Criteria andMerchantSecretkeyLessThanOrEqualTo(String value) {
            addCriterion("merchant_secretkey <=", value, "merchantSecretkey");
            return (Criteria) this;
        }

        public Criteria andMerchantSecretkeyLike(String value) {
            addCriterion("merchant_secretkey like", value, "merchantSecretkey");
            return (Criteria) this;
        }

        public Criteria andMerchantSecretkeyNotLike(String value) {
            addCriterion("merchant_secretkey not like", value, "merchantSecretkey");
            return (Criteria) this;
        }

        public Criteria andMerchantSecretkeyIn(List<String> values) {
            addCriterion("merchant_secretkey in", values, "merchantSecretkey");
            return (Criteria) this;
        }

        public Criteria andMerchantSecretkeyNotIn(List<String> values) {
            addCriterion("merchant_secretkey not in", values, "merchantSecretkey");
            return (Criteria) this;
        }

        public Criteria andMerchantSecretkeyBetween(String value1, String value2) {
            addCriterion("merchant_secretkey between", value1, value2, "merchantSecretkey");
            return (Criteria) this;
        }

        public Criteria andMerchantSecretkeyNotBetween(String value1, String value2) {
            addCriterion("merchant_secretkey not between", value1, value2, "merchantSecretkey");
            return (Criteria) this;
        }

        public Criteria andIfOpenErpIsNull() {
            addCriterion("if_open_erp is null");
            return (Criteria) this;
        }

        public Criteria andIfOpenErpIsNotNull() {
            addCriterion("if_open_erp is not null");
            return (Criteria) this;
        }

        public Criteria andIfOpenErpEqualTo(String value) {
            addCriterion("if_open_erp =", value, "ifOpenErp");
            return (Criteria) this;
        }

        public Criteria andIfOpenErpNotEqualTo(String value) {
            addCriterion("if_open_erp <>", value, "ifOpenErp");
            return (Criteria) this;
        }

        public Criteria andIfOpenErpGreaterThan(String value) {
            addCriterion("if_open_erp >", value, "ifOpenErp");
            return (Criteria) this;
        }

        public Criteria andIfOpenErpGreaterThanOrEqualTo(String value) {
            addCriterion("if_open_erp >=", value, "ifOpenErp");
            return (Criteria) this;
        }

        public Criteria andIfOpenErpLessThan(String value) {
            addCriterion("if_open_erp <", value, "ifOpenErp");
            return (Criteria) this;
        }

        public Criteria andIfOpenErpLessThanOrEqualTo(String value) {
            addCriterion("if_open_erp <=", value, "ifOpenErp");
            return (Criteria) this;
        }

        public Criteria andIfOpenErpLike(String value) {
            addCriterion("if_open_erp like", value, "ifOpenErp");
            return (Criteria) this;
        }

        public Criteria andIfOpenErpNotLike(String value) {
            addCriterion("if_open_erp not like", value, "ifOpenErp");
            return (Criteria) this;
        }

        public Criteria andIfOpenErpIn(List<String> values) {
            addCriterion("if_open_erp in", values, "ifOpenErp");
            return (Criteria) this;
        }

        public Criteria andIfOpenErpNotIn(List<String> values) {
            addCriterion("if_open_erp not in", values, "ifOpenErp");
            return (Criteria) this;
        }

        public Criteria andIfOpenErpBetween(String value1, String value2) {
            addCriterion("if_open_erp between", value1, value2, "ifOpenErp");
            return (Criteria) this;
        }

        public Criteria andIfOpenErpNotBetween(String value1, String value2) {
            addCriterion("if_open_erp not between", value1, value2, "ifOpenErp");
            return (Criteria) this;
        }

        public Criteria andIfOpenQrcodeIsNull() {
            addCriterion("if_open_qrcode is null");
            return (Criteria) this;
        }

        public Criteria andIfOpenQrcodeIsNotNull() {
            addCriterion("if_open_qrcode is not null");
            return (Criteria) this;
        }

        public Criteria andIfOpenQrcodeEqualTo(String value) {
            addCriterion("if_open_qrcode =", value, "ifOpenQrcode");
            return (Criteria) this;
        }

        public Criteria andIfOpenQrcodeNotEqualTo(String value) {
            addCriterion("if_open_qrcode <>", value, "ifOpenQrcode");
            return (Criteria) this;
        }

        public Criteria andIfOpenQrcodeGreaterThan(String value) {
            addCriterion("if_open_qrcode >", value, "ifOpenQrcode");
            return (Criteria) this;
        }

        public Criteria andIfOpenQrcodeGreaterThanOrEqualTo(String value) {
            addCriterion("if_open_qrcode >=", value, "ifOpenQrcode");
            return (Criteria) this;
        }

        public Criteria andIfOpenQrcodeLessThan(String value) {
            addCriterion("if_open_qrcode <", value, "ifOpenQrcode");
            return (Criteria) this;
        }

        public Criteria andIfOpenQrcodeLessThanOrEqualTo(String value) {
            addCriterion("if_open_qrcode <=", value, "ifOpenQrcode");
            return (Criteria) this;
        }

        public Criteria andIfOpenQrcodeLike(String value) {
            addCriterion("if_open_qrcode like", value, "ifOpenQrcode");
            return (Criteria) this;
        }

        public Criteria andIfOpenQrcodeNotLike(String value) {
            addCriterion("if_open_qrcode not like", value, "ifOpenQrcode");
            return (Criteria) this;
        }

        public Criteria andIfOpenQrcodeIn(List<String> values) {
            addCriterion("if_open_qrcode in", values, "ifOpenQrcode");
            return (Criteria) this;
        }

        public Criteria andIfOpenQrcodeNotIn(List<String> values) {
            addCriterion("if_open_qrcode not in", values, "ifOpenQrcode");
            return (Criteria) this;
        }

        public Criteria andIfOpenQrcodeBetween(String value1, String value2) {
            addCriterion("if_open_qrcode between", value1, value2, "ifOpenQrcode");
            return (Criteria) this;
        }

        public Criteria andIfOpenQrcodeNotBetween(String value1, String value2) {
            addCriterion("if_open_qrcode not between", value1, value2, "ifOpenQrcode");
            return (Criteria) this;
        }

        public Criteria andQrcodeTypeIsNull() {
            addCriterion("qrcode_type is null");
            return (Criteria) this;
        }

        public Criteria andQrcodeTypeIsNotNull() {
            addCriterion("qrcode_type is not null");
            return (Criteria) this;
        }

        public Criteria andQrcodeTypeEqualTo(String value) {
            addCriterion("qrcode_type =", value, "qrcodeType");
            return (Criteria) this;
        }

        public Criteria andQrcodeTypeNotEqualTo(String value) {
            addCriterion("qrcode_type <>", value, "qrcodeType");
            return (Criteria) this;
        }

        public Criteria andQrcodeTypeGreaterThan(String value) {
            addCriterion("qrcode_type >", value, "qrcodeType");
            return (Criteria) this;
        }

        public Criteria andQrcodeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("qrcode_type >=", value, "qrcodeType");
            return (Criteria) this;
        }

        public Criteria andQrcodeTypeLessThan(String value) {
            addCriterion("qrcode_type <", value, "qrcodeType");
            return (Criteria) this;
        }

        public Criteria andQrcodeTypeLessThanOrEqualTo(String value) {
            addCriterion("qrcode_type <=", value, "qrcodeType");
            return (Criteria) this;
        }

        public Criteria andQrcodeTypeLike(String value) {
            addCriterion("qrcode_type like", value, "qrcodeType");
            return (Criteria) this;
        }

        public Criteria andQrcodeTypeNotLike(String value) {
            addCriterion("qrcode_type not like", value, "qrcodeType");
            return (Criteria) this;
        }

        public Criteria andQrcodeTypeIn(List<String> values) {
            addCriterion("qrcode_type in", values, "qrcodeType");
            return (Criteria) this;
        }

        public Criteria andQrcodeTypeNotIn(List<String> values) {
            addCriterion("qrcode_type not in", values, "qrcodeType");
            return (Criteria) this;
        }

        public Criteria andQrcodeTypeBetween(String value1, String value2) {
            addCriterion("qrcode_type between", value1, value2, "qrcodeType");
            return (Criteria) this;
        }

        public Criteria andQrcodeTypeNotBetween(String value1, String value2) {
            addCriterion("qrcode_type not between", value1, value2, "qrcodeType");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlIsNull() {
            addCriterion("qrcode_url is null");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlIsNotNull() {
            addCriterion("qrcode_url is not null");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlEqualTo(String value) {
            addCriterion("qrcode_url =", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlNotEqualTo(String value) {
            addCriterion("qrcode_url <>", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlGreaterThan(String value) {
            addCriterion("qrcode_url >", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlGreaterThanOrEqualTo(String value) {
            addCriterion("qrcode_url >=", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlLessThan(String value) {
            addCriterion("qrcode_url <", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlLessThanOrEqualTo(String value) {
            addCriterion("qrcode_url <=", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlLike(String value) {
            addCriterion("qrcode_url like", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlNotLike(String value) {
            addCriterion("qrcode_url not like", value, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlIn(List<String> values) {
            addCriterion("qrcode_url in", values, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlNotIn(List<String> values) {
            addCriterion("qrcode_url not in", values, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlBetween(String value1, String value2) {
            addCriterion("qrcode_url between", value1, value2, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andQrcodeUrlNotBetween(String value1, String value2) {
            addCriterion("qrcode_url not between", value1, value2, "qrcodeUrl");
            return (Criteria) this;
        }

        public Criteria andMerchantShorthandIsNull() {
            addCriterion("merchant_shorthand is null");
            return (Criteria) this;
        }

        public Criteria andMerchantShorthandIsNotNull() {
            addCriterion("merchant_shorthand is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantShorthandEqualTo(String value) {
            addCriterion("merchant_shorthand =", value, "merchantShorthand");
            return (Criteria) this;
        }

        public Criteria andMerchantShorthandNotEqualTo(String value) {
            addCriterion("merchant_shorthand <>", value, "merchantShorthand");
            return (Criteria) this;
        }

        public Criteria andMerchantShorthandGreaterThan(String value) {
            addCriterion("merchant_shorthand >", value, "merchantShorthand");
            return (Criteria) this;
        }

        public Criteria andMerchantShorthandGreaterThanOrEqualTo(String value) {
            addCriterion("merchant_shorthand >=", value, "merchantShorthand");
            return (Criteria) this;
        }

        public Criteria andMerchantShorthandLessThan(String value) {
            addCriterion("merchant_shorthand <", value, "merchantShorthand");
            return (Criteria) this;
        }

        public Criteria andMerchantShorthandLessThanOrEqualTo(String value) {
            addCriterion("merchant_shorthand <=", value, "merchantShorthand");
            return (Criteria) this;
        }

        public Criteria andMerchantShorthandLike(String value) {
            addCriterion("merchant_shorthand like", value, "merchantShorthand");
            return (Criteria) this;
        }

        public Criteria andMerchantShorthandNotLike(String value) {
            addCriterion("merchant_shorthand not like", value, "merchantShorthand");
            return (Criteria) this;
        }

        public Criteria andMerchantShorthandIn(List<String> values) {
            addCriterion("merchant_shorthand in", values, "merchantShorthand");
            return (Criteria) this;
        }

        public Criteria andMerchantShorthandNotIn(List<String> values) {
            addCriterion("merchant_shorthand not in", values, "merchantShorthand");
            return (Criteria) this;
        }

        public Criteria andMerchantShorthandBetween(String value1, String value2) {
            addCriterion("merchant_shorthand between", value1, value2, "merchantShorthand");
            return (Criteria) this;
        }

        public Criteria andMerchantShorthandNotBetween(String value1, String value2) {
            addCriterion("merchant_shorthand not between", value1, value2, "merchantShorthand");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoKeyIsNull() {
            addCriterion("merchant_logo_key is null");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoKeyIsNotNull() {
            addCriterion("merchant_logo_key is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoKeyEqualTo(String value) {
            addCriterion("merchant_logo_key =", value, "merchantLogoKey");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoKeyNotEqualTo(String value) {
            addCriterion("merchant_logo_key <>", value, "merchantLogoKey");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoKeyGreaterThan(String value) {
            addCriterion("merchant_logo_key >", value, "merchantLogoKey");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoKeyGreaterThanOrEqualTo(String value) {
            addCriterion("merchant_logo_key >=", value, "merchantLogoKey");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoKeyLessThan(String value) {
            addCriterion("merchant_logo_key <", value, "merchantLogoKey");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoKeyLessThanOrEqualTo(String value) {
            addCriterion("merchant_logo_key <=", value, "merchantLogoKey");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoKeyLike(String value) {
            addCriterion("merchant_logo_key like", value, "merchantLogoKey");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoKeyNotLike(String value) {
            addCriterion("merchant_logo_key not like", value, "merchantLogoKey");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoKeyIn(List<String> values) {
            addCriterion("merchant_logo_key in", values, "merchantLogoKey");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoKeyNotIn(List<String> values) {
            addCriterion("merchant_logo_key not in", values, "merchantLogoKey");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoKeyBetween(String value1, String value2) {
            addCriterion("merchant_logo_key between", value1, value2, "merchantLogoKey");
            return (Criteria) this;
        }

        public Criteria andMerchantLogoKeyNotBetween(String value1, String value2) {
            addCriterion("merchant_logo_key not between", value1, value2, "merchantLogoKey");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("operator like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("operator not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNull() {
            addCriterion("operator_id is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNotNull() {
            addCriterion("operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdEqualTo(Long value) {
            addCriterion("operator_id =", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotEqualTo(Long value) {
            addCriterion("operator_id <>", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThan(Long value) {
            addCriterion("operator_id >", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("operator_id >=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThan(Long value) {
            addCriterion("operator_id <", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThanOrEqualTo(Long value) {
            addCriterion("operator_id <=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIn(List<Long> values) {
            addCriterion("operator_id in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotIn(List<Long> values) {
            addCriterion("operator_id not in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdBetween(Long value1, Long value2) {
            addCriterion("operator_id between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotBetween(Long value1, Long value2) {
            addCriterion("operator_id not between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIsNull() {
            addCriterion("province_id is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIsNotNull() {
            addCriterion("province_id is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceIdEqualTo(Integer value) {
            addCriterion("province_id =", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotEqualTo(Integer value) {
            addCriterion("province_id <>", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdGreaterThan(Integer value) {
            addCriterion("province_id >", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("province_id >=", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdLessThan(Integer value) {
            addCriterion("province_id <", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdLessThanOrEqualTo(Integer value) {
            addCriterion("province_id <=", value, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdIn(List<Integer> values) {
            addCriterion("province_id in", values, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotIn(List<Integer> values) {
            addCriterion("province_id not in", values, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdBetween(Integer value1, Integer value2) {
            addCriterion("province_id between", value1, value2, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceIdNotBetween(Integer value1, Integer value2) {
            addCriterion("province_id not between", value1, value2, "provinceId");
            return (Criteria) this;
        }

        public Criteria andProvinceNameIsNull() {
            addCriterion("province_name is null");
            return (Criteria) this;
        }

        public Criteria andProvinceNameIsNotNull() {
            addCriterion("province_name is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceNameEqualTo(String value) {
            addCriterion("province_name =", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotEqualTo(String value) {
            addCriterion("province_name <>", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameGreaterThan(String value) {
            addCriterion("province_name >", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameGreaterThanOrEqualTo(String value) {
            addCriterion("province_name >=", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameLessThan(String value) {
            addCriterion("province_name <", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameLessThanOrEqualTo(String value) {
            addCriterion("province_name <=", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameLike(String value) {
            addCriterion("province_name like", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotLike(String value) {
            addCriterion("province_name not like", value, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameIn(List<String> values) {
            addCriterion("province_name in", values, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotIn(List<String> values) {
            addCriterion("province_name not in", values, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameBetween(String value1, String value2) {
            addCriterion("province_name between", value1, value2, "provinceName");
            return (Criteria) this;
        }

        public Criteria andProvinceNameNotBetween(String value1, String value2) {
            addCriterion("province_name not between", value1, value2, "provinceName");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("city_id is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("city_id is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(Integer value) {
            addCriterion("city_id =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(Integer value) {
            addCriterion("city_id <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(Integer value) {
            addCriterion("city_id >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("city_id >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(Integer value) {
            addCriterion("city_id <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(Integer value) {
            addCriterion("city_id <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<Integer> values) {
            addCriterion("city_id in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<Integer> values) {
            addCriterion("city_id not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(Integer value1, Integer value2) {
            addCriterion("city_id between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(Integer value1, Integer value2) {
            addCriterion("city_id not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNull() {
            addCriterion("city_name is null");
            return (Criteria) this;
        }

        public Criteria andCityNameIsNotNull() {
            addCriterion("city_name is not null");
            return (Criteria) this;
        }

        public Criteria andCityNameEqualTo(String value) {
            addCriterion("city_name =", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotEqualTo(String value) {
            addCriterion("city_name <>", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThan(String value) {
            addCriterion("city_name >", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameGreaterThanOrEqualTo(String value) {
            addCriterion("city_name >=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThan(String value) {
            addCriterion("city_name <", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLessThanOrEqualTo(String value) {
            addCriterion("city_name <=", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameLike(String value) {
            addCriterion("city_name like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotLike(String value) {
            addCriterion("city_name not like", value, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameIn(List<String> values) {
            addCriterion("city_name in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotIn(List<String> values) {
            addCriterion("city_name not in", values, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameBetween(String value1, String value2) {
            addCriterion("city_name between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andCityNameNotBetween(String value1, String value2) {
            addCriterion("city_name not between", value1, value2, "cityName");
            return (Criteria) this;
        }

        public Criteria andCountyIdIsNull() {
            addCriterion("county_id is null");
            return (Criteria) this;
        }

        public Criteria andCountyIdIsNotNull() {
            addCriterion("county_id is not null");
            return (Criteria) this;
        }

        public Criteria andCountyIdEqualTo(Integer value) {
            addCriterion("county_id =", value, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdNotEqualTo(Integer value) {
            addCriterion("county_id <>", value, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdGreaterThan(Integer value) {
            addCriterion("county_id >", value, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("county_id >=", value, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdLessThan(Integer value) {
            addCriterion("county_id <", value, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdLessThanOrEqualTo(Integer value) {
            addCriterion("county_id <=", value, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdIn(List<Integer> values) {
            addCriterion("county_id in", values, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdNotIn(List<Integer> values) {
            addCriterion("county_id not in", values, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdBetween(Integer value1, Integer value2) {
            addCriterion("county_id between", value1, value2, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyIdNotBetween(Integer value1, Integer value2) {
            addCriterion("county_id not between", value1, value2, "countyId");
            return (Criteria) this;
        }

        public Criteria andCountyNameIsNull() {
            addCriterion("county_name is null");
            return (Criteria) this;
        }

        public Criteria andCountyNameIsNotNull() {
            addCriterion("county_name is not null");
            return (Criteria) this;
        }

        public Criteria andCountyNameEqualTo(String value) {
            addCriterion("county_name =", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameNotEqualTo(String value) {
            addCriterion("county_name <>", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameGreaterThan(String value) {
            addCriterion("county_name >", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameGreaterThanOrEqualTo(String value) {
            addCriterion("county_name >=", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameLessThan(String value) {
            addCriterion("county_name <", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameLessThanOrEqualTo(String value) {
            addCriterion("county_name <=", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameLike(String value) {
            addCriterion("county_name like", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameNotLike(String value) {
            addCriterion("county_name not like", value, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameIn(List<String> values) {
            addCriterion("county_name in", values, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameNotIn(List<String> values) {
            addCriterion("county_name not in", values, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameBetween(String value1, String value2) {
            addCriterion("county_name between", value1, value2, "countyName");
            return (Criteria) this;
        }

        public Criteria andCountyNameNotBetween(String value1, String value2) {
            addCriterion("county_name not between", value1, value2, "countyName");
            return (Criteria) this;
        }

        public Criteria andTownIdIsNull() {
            addCriterion("town_id is null");
            return (Criteria) this;
        }

        public Criteria andTownIdIsNotNull() {
            addCriterion("town_id is not null");
            return (Criteria) this;
        }

        public Criteria andTownIdEqualTo(Integer value) {
            addCriterion("town_id =", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdNotEqualTo(Integer value) {
            addCriterion("town_id <>", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdGreaterThan(Integer value) {
            addCriterion("town_id >", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("town_id >=", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdLessThan(Integer value) {
            addCriterion("town_id <", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdLessThanOrEqualTo(Integer value) {
            addCriterion("town_id <=", value, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdIn(List<Integer> values) {
            addCriterion("town_id in", values, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdNotIn(List<Integer> values) {
            addCriterion("town_id not in", values, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdBetween(Integer value1, Integer value2) {
            addCriterion("town_id between", value1, value2, "townId");
            return (Criteria) this;
        }

        public Criteria andTownIdNotBetween(Integer value1, Integer value2) {
            addCriterion("town_id not between", value1, value2, "townId");
            return (Criteria) this;
        }

        public Criteria andTownNameIsNull() {
            addCriterion("town_name is null");
            return (Criteria) this;
        }

        public Criteria andTownNameIsNotNull() {
            addCriterion("town_name is not null");
            return (Criteria) this;
        }

        public Criteria andTownNameEqualTo(String value) {
            addCriterion("town_name =", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameNotEqualTo(String value) {
            addCriterion("town_name <>", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameGreaterThan(String value) {
            addCriterion("town_name >", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameGreaterThanOrEqualTo(String value) {
            addCriterion("town_name >=", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameLessThan(String value) {
            addCriterion("town_name <", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameLessThanOrEqualTo(String value) {
            addCriterion("town_name <=", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameLike(String value) {
            addCriterion("town_name like", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameNotLike(String value) {
            addCriterion("town_name not like", value, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameIn(List<String> values) {
            addCriterion("town_name in", values, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameNotIn(List<String> values) {
            addCriterion("town_name not in", values, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameBetween(String value1, String value2) {
            addCriterion("town_name between", value1, value2, "townName");
            return (Criteria) this;
        }

        public Criteria andTownNameNotBetween(String value1, String value2) {
            addCriterion("town_name not between", value1, value2, "townName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table epl_merchant
     *
     * @mbg.generated do_not_delete_during_merge Mon Jan 01 17:03:29 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table epl_merchant
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}