package com.plc.gjw.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EplUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public EplUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUserAccountIsNull() {
            addCriterion("user_account is null");
            return (Criteria) this;
        }

        public Criteria andUserAccountIsNotNull() {
            addCriterion("user_account is not null");
            return (Criteria) this;
        }

        public Criteria andUserAccountEqualTo(String value) {
            addCriterion("user_account =", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotEqualTo(String value) {
            addCriterion("user_account <>", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountGreaterThan(String value) {
            addCriterion("user_account >", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountGreaterThanOrEqualTo(String value) {
            addCriterion("user_account >=", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountLessThan(String value) {
            addCriterion("user_account <", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountLessThanOrEqualTo(String value) {
            addCriterion("user_account <=", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountLike(String value) {
            addCriterion("user_account like", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotLike(String value) {
            addCriterion("user_account not like", value, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountIn(List<String> values) {
            addCriterion("user_account in", values, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotIn(List<String> values) {
            addCriterion("user_account not in", values, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountBetween(String value1, String value2) {
            addCriterion("user_account between", value1, value2, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserAccountNotBetween(String value1, String value2) {
            addCriterion("user_account not between", value1, value2, "userAccount");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNull() {
            addCriterion("user_type is null");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNotNull() {
            addCriterion("user_type is not null");
            return (Criteria) this;
        }

        public Criteria andUserTypeEqualTo(String value) {
            addCriterion("user_type =", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotEqualTo(String value) {
            addCriterion("user_type <>", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThan(String value) {
            addCriterion("user_type >", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("user_type >=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThan(String value) {
            addCriterion("user_type <", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThanOrEqualTo(String value) {
            addCriterion("user_type <=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLike(String value) {
            addCriterion("user_type like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotLike(String value) {
            addCriterion("user_type not like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeIn(List<String> values) {
            addCriterion("user_type in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotIn(List<String> values) {
            addCriterion("user_type not in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeBetween(String value1, String value2) {
            addCriterion("user_type between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotBetween(String value1, String value2) {
            addCriterion("user_type not between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNull() {
            addCriterion("user_password is null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNotNull() {
            addCriterion("user_password is not null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordEqualTo(String value) {
            addCriterion("user_password =", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotEqualTo(String value) {
            addCriterion("user_password <>", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThan(String value) {
            addCriterion("user_password >", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("user_password >=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThan(String value) {
            addCriterion("user_password <", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("user_password <=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLike(String value) {
            addCriterion("user_password like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotLike(String value) {
            addCriterion("user_password not like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIn(List<String> values) {
            addCriterion("user_password in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotIn(List<String> values) {
            addCriterion("user_password not in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordBetween(String value1, String value2) {
            addCriterion("user_password between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotBetween(String value1, String value2) {
            addCriterion("user_password not between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("real_name is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("real_name is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("real_name =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("real_name <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("real_name >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("real_name >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("real_name <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("real_name <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("real_name like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("real_name not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("real_name in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("real_name not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("real_name between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("real_name not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andPasswdEffectTimeIsNull() {
            addCriterion("passwd_effect_time is null");
            return (Criteria) this;
        }

        public Criteria andPasswdEffectTimeIsNotNull() {
            addCriterion("passwd_effect_time is not null");
            return (Criteria) this;
        }

        public Criteria andPasswdEffectTimeEqualTo(Date value) {
            addCriterion("passwd_effect_time =", value, "passwdEffectTime");
            return (Criteria) this;
        }

        public Criteria andPasswdEffectTimeNotEqualTo(Date value) {
            addCriterion("passwd_effect_time <>", value, "passwdEffectTime");
            return (Criteria) this;
        }

        public Criteria andPasswdEffectTimeGreaterThan(Date value) {
            addCriterion("passwd_effect_time >", value, "passwdEffectTime");
            return (Criteria) this;
        }

        public Criteria andPasswdEffectTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("passwd_effect_time >=", value, "passwdEffectTime");
            return (Criteria) this;
        }

        public Criteria andPasswdEffectTimeLessThan(Date value) {
            addCriterion("passwd_effect_time <", value, "passwdEffectTime");
            return (Criteria) this;
        }

        public Criteria andPasswdEffectTimeLessThanOrEqualTo(Date value) {
            addCriterion("passwd_effect_time <=", value, "passwdEffectTime");
            return (Criteria) this;
        }

        public Criteria andPasswdEffectTimeIn(List<Date> values) {
            addCriterion("passwd_effect_time in", values, "passwdEffectTime");
            return (Criteria) this;
        }

        public Criteria andPasswdEffectTimeNotIn(List<Date> values) {
            addCriterion("passwd_effect_time not in", values, "passwdEffectTime");
            return (Criteria) this;
        }

        public Criteria andPasswdEffectTimeBetween(Date value1, Date value2) {
            addCriterion("passwd_effect_time between", value1, value2, "passwdEffectTime");
            return (Criteria) this;
        }

        public Criteria andPasswdEffectTimeNotBetween(Date value1, Date value2) {
            addCriterion("passwd_effect_time not between", value1, value2, "passwdEffectTime");
            return (Criteria) this;
        }

        public Criteria andPasswdExpireTimeIsNull() {
            addCriterion("passwd_expire_time is null");
            return (Criteria) this;
        }

        public Criteria andPasswdExpireTimeIsNotNull() {
            addCriterion("passwd_expire_time is not null");
            return (Criteria) this;
        }

        public Criteria andPasswdExpireTimeEqualTo(Date value) {
            addCriterion("passwd_expire_time =", value, "passwdExpireTime");
            return (Criteria) this;
        }

        public Criteria andPasswdExpireTimeNotEqualTo(Date value) {
            addCriterion("passwd_expire_time <>", value, "passwdExpireTime");
            return (Criteria) this;
        }

        public Criteria andPasswdExpireTimeGreaterThan(Date value) {
            addCriterion("passwd_expire_time >", value, "passwdExpireTime");
            return (Criteria) this;
        }

        public Criteria andPasswdExpireTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("passwd_expire_time >=", value, "passwdExpireTime");
            return (Criteria) this;
        }

        public Criteria andPasswdExpireTimeLessThan(Date value) {
            addCriterion("passwd_expire_time <", value, "passwdExpireTime");
            return (Criteria) this;
        }

        public Criteria andPasswdExpireTimeLessThanOrEqualTo(Date value) {
            addCriterion("passwd_expire_time <=", value, "passwdExpireTime");
            return (Criteria) this;
        }

        public Criteria andPasswdExpireTimeIn(List<Date> values) {
            addCriterion("passwd_expire_time in", values, "passwdExpireTime");
            return (Criteria) this;
        }

        public Criteria andPasswdExpireTimeNotIn(List<Date> values) {
            addCriterion("passwd_expire_time not in", values, "passwdExpireTime");
            return (Criteria) this;
        }

        public Criteria andPasswdExpireTimeBetween(Date value1, Date value2) {
            addCriterion("passwd_expire_time between", value1, value2, "passwdExpireTime");
            return (Criteria) this;
        }

        public Criteria andPasswdExpireTimeNotBetween(Date value1, Date value2) {
            addCriterion("passwd_expire_time not between", value1, value2, "passwdExpireTime");
            return (Criteria) this;
        }

        public Criteria andPasswdModifyTimeIsNull() {
            addCriterion("passwd_modify_time is null");
            return (Criteria) this;
        }

        public Criteria andPasswdModifyTimeIsNotNull() {
            addCriterion("passwd_modify_time is not null");
            return (Criteria) this;
        }

        public Criteria andPasswdModifyTimeEqualTo(Date value) {
            addCriterion("passwd_modify_time =", value, "passwdModifyTime");
            return (Criteria) this;
        }

        public Criteria andPasswdModifyTimeNotEqualTo(Date value) {
            addCriterion("passwd_modify_time <>", value, "passwdModifyTime");
            return (Criteria) this;
        }

        public Criteria andPasswdModifyTimeGreaterThan(Date value) {
            addCriterion("passwd_modify_time >", value, "passwdModifyTime");
            return (Criteria) this;
        }

        public Criteria andPasswdModifyTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("passwd_modify_time >=", value, "passwdModifyTime");
            return (Criteria) this;
        }

        public Criteria andPasswdModifyTimeLessThan(Date value) {
            addCriterion("passwd_modify_time <", value, "passwdModifyTime");
            return (Criteria) this;
        }

        public Criteria andPasswdModifyTimeLessThanOrEqualTo(Date value) {
            addCriterion("passwd_modify_time <=", value, "passwdModifyTime");
            return (Criteria) this;
        }

        public Criteria andPasswdModifyTimeIn(List<Date> values) {
            addCriterion("passwd_modify_time in", values, "passwdModifyTime");
            return (Criteria) this;
        }

        public Criteria andPasswdModifyTimeNotIn(List<Date> values) {
            addCriterion("passwd_modify_time not in", values, "passwdModifyTime");
            return (Criteria) this;
        }

        public Criteria andPasswdModifyTimeBetween(Date value1, Date value2) {
            addCriterion("passwd_modify_time between", value1, value2, "passwdModifyTime");
            return (Criteria) this;
        }

        public Criteria andPasswdModifyTimeNotBetween(Date value1, Date value2) {
            addCriterion("passwd_modify_time not between", value1, value2, "passwdModifyTime");
            return (Criteria) this;
        }

        public Criteria andReloginFlagIsNull() {
            addCriterion("relogin_flag is null");
            return (Criteria) this;
        }

        public Criteria andReloginFlagIsNotNull() {
            addCriterion("relogin_flag is not null");
            return (Criteria) this;
        }

        public Criteria andReloginFlagEqualTo(String value) {
            addCriterion("relogin_flag =", value, "reloginFlag");
            return (Criteria) this;
        }

        public Criteria andReloginFlagNotEqualTo(String value) {
            addCriterion("relogin_flag <>", value, "reloginFlag");
            return (Criteria) this;
        }

        public Criteria andReloginFlagGreaterThan(String value) {
            addCriterion("relogin_flag >", value, "reloginFlag");
            return (Criteria) this;
        }

        public Criteria andReloginFlagGreaterThanOrEqualTo(String value) {
            addCriterion("relogin_flag >=", value, "reloginFlag");
            return (Criteria) this;
        }

        public Criteria andReloginFlagLessThan(String value) {
            addCriterion("relogin_flag <", value, "reloginFlag");
            return (Criteria) this;
        }

        public Criteria andReloginFlagLessThanOrEqualTo(String value) {
            addCriterion("relogin_flag <=", value, "reloginFlag");
            return (Criteria) this;
        }

        public Criteria andReloginFlagLike(String value) {
            addCriterion("relogin_flag like", value, "reloginFlag");
            return (Criteria) this;
        }

        public Criteria andReloginFlagNotLike(String value) {
            addCriterion("relogin_flag not like", value, "reloginFlag");
            return (Criteria) this;
        }

        public Criteria andReloginFlagIn(List<String> values) {
            addCriterion("relogin_flag in", values, "reloginFlag");
            return (Criteria) this;
        }

        public Criteria andReloginFlagNotIn(List<String> values) {
            addCriterion("relogin_flag not in", values, "reloginFlag");
            return (Criteria) this;
        }

        public Criteria andReloginFlagBetween(String value1, String value2) {
            addCriterion("relogin_flag between", value1, value2, "reloginFlag");
            return (Criteria) this;
        }

        public Criteria andReloginFlagNotBetween(String value1, String value2) {
            addCriterion("relogin_flag not between", value1, value2, "reloginFlag");
            return (Criteria) this;
        }

        public Criteria andReloginCountIsNull() {
            addCriterion("relogin_count is null");
            return (Criteria) this;
        }

        public Criteria andReloginCountIsNotNull() {
            addCriterion("relogin_count is not null");
            return (Criteria) this;
        }

        public Criteria andReloginCountEqualTo(String value) {
            addCriterion("relogin_count =", value, "reloginCount");
            return (Criteria) this;
        }

        public Criteria andReloginCountNotEqualTo(String value) {
            addCriterion("relogin_count <>", value, "reloginCount");
            return (Criteria) this;
        }

        public Criteria andReloginCountGreaterThan(String value) {
            addCriterion("relogin_count >", value, "reloginCount");
            return (Criteria) this;
        }

        public Criteria andReloginCountGreaterThanOrEqualTo(String value) {
            addCriterion("relogin_count >=", value, "reloginCount");
            return (Criteria) this;
        }

        public Criteria andReloginCountLessThan(String value) {
            addCriterion("relogin_count <", value, "reloginCount");
            return (Criteria) this;
        }

        public Criteria andReloginCountLessThanOrEqualTo(String value) {
            addCriterion("relogin_count <=", value, "reloginCount");
            return (Criteria) this;
        }

        public Criteria andReloginCountLike(String value) {
            addCriterion("relogin_count like", value, "reloginCount");
            return (Criteria) this;
        }

        public Criteria andReloginCountNotLike(String value) {
            addCriterion("relogin_count not like", value, "reloginCount");
            return (Criteria) this;
        }

        public Criteria andReloginCountIn(List<String> values) {
            addCriterion("relogin_count in", values, "reloginCount");
            return (Criteria) this;
        }

        public Criteria andReloginCountNotIn(List<String> values) {
            addCriterion("relogin_count not in", values, "reloginCount");
            return (Criteria) this;
        }

        public Criteria andReloginCountBetween(String value1, String value2) {
            addCriterion("relogin_count between", value1, value2, "reloginCount");
            return (Criteria) this;
        }

        public Criteria andReloginCountNotBetween(String value1, String value2) {
            addCriterion("relogin_count not between", value1, value2, "reloginCount");
            return (Criteria) this;
        }

        public Criteria andLastLoginErrorTimeIsNull() {
            addCriterion("last_login_error_time is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginErrorTimeIsNotNull() {
            addCriterion("last_login_error_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginErrorTimeEqualTo(Date value) {
            addCriterion("last_login_error_time =", value, "lastLoginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginErrorTimeNotEqualTo(Date value) {
            addCriterion("last_login_error_time <>", value, "lastLoginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginErrorTimeGreaterThan(Date value) {
            addCriterion("last_login_error_time >", value, "lastLoginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginErrorTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_login_error_time >=", value, "lastLoginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginErrorTimeLessThan(Date value) {
            addCriterion("last_login_error_time <", value, "lastLoginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginErrorTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_login_error_time <=", value, "lastLoginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginErrorTimeIn(List<Date> values) {
            addCriterion("last_login_error_time in", values, "lastLoginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginErrorTimeNotIn(List<Date> values) {
            addCriterion("last_login_error_time not in", values, "lastLoginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginErrorTimeBetween(Date value1, Date value2) {
            addCriterion("last_login_error_time between", value1, value2, "lastLoginErrorTime");
            return (Criteria) this;
        }

        public Criteria andLastLoginErrorTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_login_error_time not between", value1, value2, "lastLoginErrorTime");
            return (Criteria) this;
        }

        public Criteria andPasswordModifyCycleIsNull() {
            addCriterion("password_modify_cycle is null");
            return (Criteria) this;
        }

        public Criteria andPasswordModifyCycleIsNotNull() {
            addCriterion("password_modify_cycle is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordModifyCycleEqualTo(Integer value) {
            addCriterion("password_modify_cycle =", value, "passwordModifyCycle");
            return (Criteria) this;
        }

        public Criteria andPasswordModifyCycleNotEqualTo(Integer value) {
            addCriterion("password_modify_cycle <>", value, "passwordModifyCycle");
            return (Criteria) this;
        }

        public Criteria andPasswordModifyCycleGreaterThan(Integer value) {
            addCriterion("password_modify_cycle >", value, "passwordModifyCycle");
            return (Criteria) this;
        }

        public Criteria andPasswordModifyCycleGreaterThanOrEqualTo(Integer value) {
            addCriterion("password_modify_cycle >=", value, "passwordModifyCycle");
            return (Criteria) this;
        }

        public Criteria andPasswordModifyCycleLessThan(Integer value) {
            addCriterion("password_modify_cycle <", value, "passwordModifyCycle");
            return (Criteria) this;
        }

        public Criteria andPasswordModifyCycleLessThanOrEqualTo(Integer value) {
            addCriterion("password_modify_cycle <=", value, "passwordModifyCycle");
            return (Criteria) this;
        }

        public Criteria andPasswordModifyCycleIn(List<Integer> values) {
            addCriterion("password_modify_cycle in", values, "passwordModifyCycle");
            return (Criteria) this;
        }

        public Criteria andPasswordModifyCycleNotIn(List<Integer> values) {
            addCriterion("password_modify_cycle not in", values, "passwordModifyCycle");
            return (Criteria) this;
        }

        public Criteria andPasswordModifyCycleBetween(Integer value1, Integer value2) {
            addCriterion("password_modify_cycle between", value1, value2, "passwordModifyCycle");
            return (Criteria) this;
        }

        public Criteria andPasswordModifyCycleNotBetween(Integer value1, Integer value2) {
            addCriterion("password_modify_cycle not between", value1, value2, "passwordModifyCycle");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNull() {
            addCriterion("org_code is null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNotNull() {
            addCriterion("org_code is not null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeEqualTo(String value) {
            addCriterion("org_code =", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotEqualTo(String value) {
            addCriterion("org_code <>", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThan(String value) {
            addCriterion("org_code >", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThanOrEqualTo(String value) {
            addCriterion("org_code >=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThan(String value) {
            addCriterion("org_code <", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThanOrEqualTo(String value) {
            addCriterion("org_code <=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLike(String value) {
            addCriterion("org_code like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotLike(String value) {
            addCriterion("org_code not like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIn(List<String> values) {
            addCriterion("org_code in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotIn(List<String> values) {
            addCriterion("org_code not in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeBetween(String value1, String value2) {
            addCriterion("org_code between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotBetween(String value1, String value2) {
            addCriterion("org_code not between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Long value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Long value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Long value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Long value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Long value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Long> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Long> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Long value1, Long value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Long value1, Long value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("operator like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("operator not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andMerchentIdIsNull() {
            addCriterion("merchent_id is null");
            return (Criteria) this;
        }

        public Criteria andMerchentIdIsNotNull() {
            addCriterion("merchent_id is not null");
            return (Criteria) this;
        }

        public Criteria andMerchentIdEqualTo(Long value) {
            addCriterion("merchent_id =", value, "merchentId");
            return (Criteria) this;
        }

        public Criteria andMerchentIdNotEqualTo(Long value) {
            addCriterion("merchent_id <>", value, "merchentId");
            return (Criteria) this;
        }

        public Criteria andMerchentIdGreaterThan(Long value) {
            addCriterion("merchent_id >", value, "merchentId");
            return (Criteria) this;
        }

        public Criteria andMerchentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("merchent_id >=", value, "merchentId");
            return (Criteria) this;
        }

        public Criteria andMerchentIdLessThan(Long value) {
            addCriterion("merchent_id <", value, "merchentId");
            return (Criteria) this;
        }

        public Criteria andMerchentIdLessThanOrEqualTo(Long value) {
            addCriterion("merchent_id <=", value, "merchentId");
            return (Criteria) this;
        }

        public Criteria andMerchentIdIn(List<Long> values) {
            addCriterion("merchent_id in", values, "merchentId");
            return (Criteria) this;
        }

        public Criteria andMerchentIdNotIn(List<Long> values) {
            addCriterion("merchent_id not in", values, "merchentId");
            return (Criteria) this;
        }

        public Criteria andMerchentIdBetween(Long value1, Long value2) {
            addCriterion("merchent_id between", value1, value2, "merchentId");
            return (Criteria) this;
        }

        public Criteria andMerchentIdNotBetween(Long value1, Long value2) {
            addCriterion("merchent_id not between", value1, value2, "merchentId");
            return (Criteria) this;
        }

        public Criteria andAliasIsNull() {
            addCriterion("alias is null");
            return (Criteria) this;
        }

        public Criteria andAliasIsNotNull() {
            addCriterion("alias is not null");
            return (Criteria) this;
        }

        public Criteria andAliasEqualTo(String value) {
            addCriterion("alias =", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotEqualTo(String value) {
            addCriterion("alias <>", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThan(String value) {
            addCriterion("alias >", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThanOrEqualTo(String value) {
            addCriterion("alias >=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThan(String value) {
            addCriterion("alias <", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThanOrEqualTo(String value) {
            addCriterion("alias <=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLike(String value) {
            addCriterion("alias like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotLike(String value) {
            addCriterion("alias not like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasIn(List<String> values) {
            addCriterion("alias in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotIn(List<String> values) {
            addCriterion("alias not in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasBetween(String value1, String value2) {
            addCriterion("alias between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotBetween(String value1, String value2) {
            addCriterion("alias not between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("created_date is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("created_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(Date value) {
            addCriterion("created_date =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(Date value) {
            addCriterion("created_date <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(Date value) {
            addCriterion("created_date >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("created_date >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(Date value) {
            addCriterion("created_date <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(Date value) {
            addCriterion("created_date <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<Date> values) {
            addCriterion("created_date in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<Date> values) {
            addCriterion("created_date not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(Date value1, Date value2) {
            addCriterion("created_date between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(Date value1, Date value2) {
            addCriterion("created_date not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNull() {
            addCriterion("modified_date is null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIsNotNull() {
            addCriterion("modified_date is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedDateEqualTo(Date value) {
            addCriterion("modified_date =", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotEqualTo(Date value) {
            addCriterion("modified_date <>", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThan(Date value) {
            addCriterion("modified_date >", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_date >=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThan(Date value) {
            addCriterion("modified_date <", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateLessThanOrEqualTo(Date value) {
            addCriterion("modified_date <=", value, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateIn(List<Date> values) {
            addCriterion("modified_date in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotIn(List<Date> values) {
            addCriterion("modified_date not in", values, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateBetween(Date value1, Date value2) {
            addCriterion("modified_date between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andModifiedDateNotBetween(Date value1, Date value2) {
            addCriterion("modified_date not between", value1, value2, "modifiedDate");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNull() {
            addCriterion("operator_id is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIsNotNull() {
            addCriterion("operator_id is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdEqualTo(Long value) {
            addCriterion("operator_id =", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotEqualTo(Long value) {
            addCriterion("operator_id <>", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThan(Long value) {
            addCriterion("operator_id >", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdGreaterThanOrEqualTo(Long value) {
            addCriterion("operator_id >=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThan(Long value) {
            addCriterion("operator_id <", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdLessThanOrEqualTo(Long value) {
            addCriterion("operator_id <=", value, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdIn(List<Long> values) {
            addCriterion("operator_id in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotIn(List<Long> values) {
            addCriterion("operator_id not in", values, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdBetween(Long value1, Long value2) {
            addCriterion("operator_id between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andOperatorIdNotBetween(Long value1, Long value2) {
            addCriterion("operator_id not between", value1, value2, "operatorId");
            return (Criteria) this;
        }

        public Criteria andPasswordSaltIsNull() {
            addCriterion("password_salt is null");
            return (Criteria) this;
        }

        public Criteria andPasswordSaltIsNotNull() {
            addCriterion("password_salt is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordSaltEqualTo(String value) {
            addCriterion("password_salt =", value, "passwordSalt");
            return (Criteria) this;
        }

        public Criteria andPasswordSaltNotEqualTo(String value) {
            addCriterion("password_salt <>", value, "passwordSalt");
            return (Criteria) this;
        }

        public Criteria andPasswordSaltGreaterThan(String value) {
            addCriterion("password_salt >", value, "passwordSalt");
            return (Criteria) this;
        }

        public Criteria andPasswordSaltGreaterThanOrEqualTo(String value) {
            addCriterion("password_salt >=", value, "passwordSalt");
            return (Criteria) this;
        }

        public Criteria andPasswordSaltLessThan(String value) {
            addCriterion("password_salt <", value, "passwordSalt");
            return (Criteria) this;
        }

        public Criteria andPasswordSaltLessThanOrEqualTo(String value) {
            addCriterion("password_salt <=", value, "passwordSalt");
            return (Criteria) this;
        }

        public Criteria andPasswordSaltLike(String value) {
            addCriterion("password_salt like", value, "passwordSalt");
            return (Criteria) this;
        }

        public Criteria andPasswordSaltNotLike(String value) {
            addCriterion("password_salt not like", value, "passwordSalt");
            return (Criteria) this;
        }

        public Criteria andPasswordSaltIn(List<String> values) {
            addCriterion("password_salt in", values, "passwordSalt");
            return (Criteria) this;
        }

        public Criteria andPasswordSaltNotIn(List<String> values) {
            addCriterion("password_salt not in", values, "passwordSalt");
            return (Criteria) this;
        }

        public Criteria andPasswordSaltBetween(String value1, String value2) {
            addCriterion("password_salt between", value1, value2, "passwordSalt");
            return (Criteria) this;
        }

        public Criteria andPasswordSaltNotBetween(String value1, String value2) {
            addCriterion("password_salt not between", value1, value2, "passwordSalt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table epl_user
     *
     * @mbg.generated do_not_delete_during_merge Mon Jan 01 17:03:29 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table epl_user
     *
     * @mbg.generated Mon Jan 01 17:03:29 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}