package com.plc.gjw.domain;

import java.math.BigDecimal;
import java.util.Date;

public class LockStock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_lock_stock.id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_lock_stock.merchant_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Long merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_lock_stock.bill_no
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String billNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_lock_stock.status
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_lock_stock.source
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_lock_stock.price
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_lock_stock.operator
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_lock_stock.operator_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Long operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_lock_stock.created_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_lock_stock.modified_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Date modifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_lock_stock.id
     *
     * @return the value of innovation_lock_stock.id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_lock_stock.id
     *
     * @param id the value for innovation_lock_stock.id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_lock_stock.merchant_id
     *
     * @return the value of innovation_lock_stock.merchant_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_lock_stock.merchant_id
     *
     * @param merchantId the value for innovation_lock_stock.merchant_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_lock_stock.bill_no
     *
     * @return the value of innovation_lock_stock.bill_no
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_lock_stock.bill_no
     *
     * @param billNo the value for innovation_lock_stock.bill_no
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo == null ? null : billNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_lock_stock.status
     *
     * @return the value of innovation_lock_stock.status
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_lock_stock.status
     *
     * @param status the value for innovation_lock_stock.status
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_lock_stock.source
     *
     * @return the value of innovation_lock_stock.source
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_lock_stock.source
     *
     * @param source the value for innovation_lock_stock.source
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_lock_stock.price
     *
     * @return the value of innovation_lock_stock.price
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_lock_stock.price
     *
     * @param price the value for innovation_lock_stock.price
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_lock_stock.operator
     *
     * @return the value of innovation_lock_stock.operator
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_lock_stock.operator
     *
     * @param operator the value for innovation_lock_stock.operator
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_lock_stock.operator_id
     *
     * @return the value of innovation_lock_stock.operator_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_lock_stock.operator_id
     *
     * @param operatorId the value for innovation_lock_stock.operator_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_lock_stock.created_date
     *
     * @return the value of innovation_lock_stock.created_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_lock_stock.created_date
     *
     * @param createdDate the value for innovation_lock_stock.created_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_lock_stock.modified_date
     *
     * @return the value of innovation_lock_stock.modified_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_lock_stock.modified_date
     *
     * @param modifiedDate the value for innovation_lock_stock.modified_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
}