package com.plc.gjw.domain;

import java.math.BigDecimal;

public class LockStockDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_lock_stock_detail.id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_lock_stock_detail.bill_no
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String billNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_lock_stock_detail.product_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_lock_stock_detail.product_count
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Integer productCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_lock_stock_detail.price
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private BigDecimal price;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_lock_stock_detail.id
     *
     * @return the value of innovation_lock_stock_detail.id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_lock_stock_detail.id
     *
     * @param id the value for innovation_lock_stock_detail.id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_lock_stock_detail.bill_no
     *
     * @return the value of innovation_lock_stock_detail.bill_no
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_lock_stock_detail.bill_no
     *
     * @param billNo the value for innovation_lock_stock_detail.bill_no
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo == null ? null : billNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_lock_stock_detail.product_id
     *
     * @return the value of innovation_lock_stock_detail.product_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_lock_stock_detail.product_id
     *
     * @param productId the value for innovation_lock_stock_detail.product_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_lock_stock_detail.product_count
     *
     * @return the value of innovation_lock_stock_detail.product_count
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_lock_stock_detail.product_count
     *
     * @param productCount the value for innovation_lock_stock_detail.product_count
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_lock_stock_detail.price
     *
     * @return the value of innovation_lock_stock_detail.price
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_lock_stock_detail.price
     *
     * @param price the value for innovation_lock_stock_detail.price
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
}