package com.plc.gjw.domain;

import java.util.Date;

public class StockBatch {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_stock_batch.id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_stock_batch.merchant_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Long merchantId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_stock_batch.product_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_stock_batch.bar_code
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String barCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_stock_batch.erp_code
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String erpCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_stock_batch.product_name
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_stock_batch.batch_no
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String batchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_stock_batch.batch_count
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Integer batchCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_stock_batch.batch_type
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String batchType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_stock_batch.source
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_stock_batch.operator
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_stock_batch.operator_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Long operatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_stock_batch.created_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Date createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column innovation_stock_batch.modified_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    private Date modifiedDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_stock_batch.id
     *
     * @return the value of innovation_stock_batch.id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_stock_batch.id
     *
     * @param id the value for innovation_stock_batch.id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_stock_batch.merchant_id
     *
     * @return the value of innovation_stock_batch.merchant_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Long getMerchantId() {
        return merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_stock_batch.merchant_id
     *
     * @param merchantId the value for innovation_stock_batch.merchant_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setMerchantId(Long merchantId) {
        this.merchantId = merchantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_stock_batch.product_id
     *
     * @return the value of innovation_stock_batch.product_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_stock_batch.product_id
     *
     * @param productId the value for innovation_stock_batch.product_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_stock_batch.bar_code
     *
     * @return the value of innovation_stock_batch.bar_code
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_stock_batch.bar_code
     *
     * @param barCode the value for innovation_stock_batch.bar_code
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_stock_batch.erp_code
     *
     * @return the value of innovation_stock_batch.erp_code
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getErpCode() {
        return erpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_stock_batch.erp_code
     *
     * @param erpCode the value for innovation_stock_batch.erp_code
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setErpCode(String erpCode) {
        this.erpCode = erpCode == null ? null : erpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_stock_batch.product_name
     *
     * @return the value of innovation_stock_batch.product_name
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_stock_batch.product_name
     *
     * @param productName the value for innovation_stock_batch.product_name
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_stock_batch.batch_no
     *
     * @return the value of innovation_stock_batch.batch_no
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getBatchNo() {
        return batchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_stock_batch.batch_no
     *
     * @param batchNo the value for innovation_stock_batch.batch_no
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setBatchNo(String batchNo) {
        this.batchNo = batchNo == null ? null : batchNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_stock_batch.batch_count
     *
     * @return the value of innovation_stock_batch.batch_count
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Integer getBatchCount() {
        return batchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_stock_batch.batch_count
     *
     * @param batchCount the value for innovation_stock_batch.batch_count
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setBatchCount(Integer batchCount) {
        this.batchCount = batchCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_stock_batch.batch_type
     *
     * @return the value of innovation_stock_batch.batch_type
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getBatchType() {
        return batchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_stock_batch.batch_type
     *
     * @param batchType the value for innovation_stock_batch.batch_type
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setBatchType(String batchType) {
        this.batchType = batchType == null ? null : batchType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_stock_batch.source
     *
     * @return the value of innovation_stock_batch.source
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_stock_batch.source
     *
     * @param source the value for innovation_stock_batch.source
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_stock_batch.operator
     *
     * @return the value of innovation_stock_batch.operator
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_stock_batch.operator
     *
     * @param operator the value for innovation_stock_batch.operator
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_stock_batch.operator_id
     *
     * @return the value of innovation_stock_batch.operator_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_stock_batch.operator_id
     *
     * @param operatorId the value for innovation_stock_batch.operator_id
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_stock_batch.created_date
     *
     * @return the value of innovation_stock_batch.created_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_stock_batch.created_date
     *
     * @param createdDate the value for innovation_stock_batch.created_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column innovation_stock_batch.modified_date
     *
     * @return the value of innovation_stock_batch.modified_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column innovation_stock_batch.modified_date
     *
     * @param modifiedDate the value for innovation_stock_batch.modified_date
     *
     * @mbg.generated Mon Jan 01 19:25:08 CST 2018
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }
}